"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { createClinicDirectPatient,createEncounter,fetchMyOrganizationCapabilities,fetchPatients } from "@/lib/api";
export default function Page(){
 const router=useRouter(); const [profile,setProfile]=useState<any>(null),[patients,setPatients]=useState<any[]>([]),[mode,setMode]=useState("existing"),[patient,setPatient]=useState(""),[route,setRoute]=useState("clinic_managed"),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({first_name:"",last_name:"",date_of_birth:"",sex:"female",phone:"",email:"",country:"Nigeria"});
 useEffect(()=>{Promise.all([fetchMyOrganizationCapabilities(),fetchPatients()]).then(([a,b])=>{setProfile(a);setPatients(b);if(a.workflow_mode!=="hybrid")setRoute(a.workflow_mode)}).catch(e=>setError(e.message))},[]);
 async function submit(){try{setSaving(true);setError("");let id=patient;if(mode==="new"){const p=await createClinicDirectPatient(form);id=String(p.id)}if(!id)throw new Error("Select or create a patient.");const e=await createEncounter({encounter_id:`ENC-${Date.now().toString().slice(-10)}`,patient:Number(id),encounter_date:new Date().toISOString().slice(0,10),encounter_type:"retinal_assessment",programme:"diabetic_screening",source_type:"clinic_direct",workflow_route:route,payment_responsibility:profile.default_payment_responsibility});router.push(`/encounters/${e.id}`)}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 if(profile&&!profile.clinic_direct_screening_enabled)return <main className="p-10">Clinic-direct screening is not enabled for this clinic.</main>;
 return <main className="sentinel-page max-w-3xl space-y-6"><div><h1 className="text-2xl font-bold">New Diabetic Retinal Assessment</h1><p className="text-sm text-slate-600">Create a clinic-owned diabetic retinal assessment without a hospital referral.</p></div>{error?<p className="rounded border border-red-200 bg-red-50 p-3 text-red-800">{error}</p>:null}<section className="rounded-xl border bg-white p-6"><div className="mb-4 flex gap-3"><button onClick={()=>setMode("existing")} className="rounded border px-3 py-2">Existing Patient</button><button onClick={()=>setMode("new")} className="rounded border px-3 py-2">New Patient</button></div>{mode==="existing"?<select value={patient} onChange={e=>setPatient(e.target.value)} className="w-full rounded border p-3"><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.patient_id} — {p.first_name} {p.last_name}</option>)}</select>:<div className="grid gap-3 md:grid-cols-2">{["first_name","last_name","date_of_birth","phone","email"].map(k=><input key={k} type={k==="date_of_birth"?"date":"text"} placeholder={k.replaceAll("_"," ")} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="rounded border p-3"/>)}<select value={form.sex} onChange={e=>setForm({...form,sex:e.target.value})} className="rounded border p-3"><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option></select></div>}</section>{profile?.workflow_mode==="hybrid"?<select value={route} onChange={e=>setRoute(e.target.value)} className="w-full rounded border p-3"><option value="clinic_managed">Clinic Managed</option><option value="sentinel_managed">Sentinel Managed</option></select>:null}<button onClick={submit} disabled={saving} className="rounded-xl bg-slate-950 px-5 py-3 font-semibold text-white disabled:opacity-50">{saving?"Creating...":"Create Assessment and Open Encounter"}</button></main>
}
