import Link from "next/link";
import { serverFetch } from "@/lib/server-api";
import type { FinanceDashboardSummary, FinanceWallet, PartnerContract, PricingRule } from "@/types/finance";
const money=(v:string)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(Number(v||0));
export default async function OpsFinanceDashboard(){
 const [summary,wallets,contracts,rules]:[FinanceDashboardSummary,FinanceWallet[],PartnerContract[],PricingRule[]]=await Promise.all([serverFetch("/api/finance/summary/"),serverFetch("/api/finance/wallets/"),serverFetch("/api/finance/contracts/"),serverFetch("/api/finance/pricing-rules/")]);
 const activeContracts=contracts.filter(c=>c.status==="active");
 const lowWallets=wallets.filter(w=>{const c=activeContracts.find(x=>x.organization===w.organization);const r=rules.find(x=>x.contract===c?.id&&x.is_active);return r&&Number(w.spendable_balance)<Number(r.gross_amount)*5;});
 const cards=[["Active contracts",summary.active_contracts],["Active pricing rules",summary.pricing_rules],["Organisation wallets",summary.wallets],["Financial records",summary.financial_records],["Awaiting payment",summary.awaiting_payment],["Captured assessments",summary.captured]];
 return <div className="space-y-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Finance</h1><p className="mt-1 text-slate-600">Contracts, negotiated pricing, wallets, ledger and settlements.</p></div><div className="flex flex-wrap gap-2"><Link href="/ops/finance/setup" className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Finance setup wizard</Link><Link href="/ops/finance/contracts" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Manage pricing</Link></div></div>
 {lowWallets.length?<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-950">Low-balance organisations</h2><p className="mt-1 text-sm text-amber-900">These wallets hold fewer than five assessments at the current negotiated price.</p><div className="mt-3 flex flex-wrap gap-2">{lowWallets.map(w=><span key={w.id} className="rounded-full bg-white px-3 py-1 text-sm font-semibold text-amber-900">{w.organization_name}: {money(w.spendable_balance)}</span>)}</div></section>:null}
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(([t,v])=><div key={String(t)} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-600">{t}</p><p className="mt-2 text-3xl font-bold">{v}</p></div>)}</section>
 <section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm text-slate-600">Total available wallet balance</p><p className="mt-2 text-3xl font-bold">{money(summary.wallet_available)}</p></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm text-slate-600">Total reserved wallet balance</p><p className="mt-2 text-3xl font-bold">{money(summary.wallet_reserved)}</p></div></section>
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Setup wizard","Onboard a hospital or clinic in one flow.","/ops/finance/setup"],["Contracts & pricing","Set organisation-specific assessment charges.","/ops/finance/contracts"],["Funding approvals","Verify and approve bank-transfer funding.","/ops/finance/funding"],["Service allowances","Control temporary pre-funding authority.","/ops/finance/allowances"],["Immutable ledger","Review every append-only wallet movement.","/ops/finance/ledger"],["Corrections","Maker–checker refunds and reversals.","/ops/finance/corrections"],["Settlements","Prepare, approve and evidence payouts.","/ops/finance/settlements"],["Reconciliation & audit","Investigate control consistency and history.","/ops/finance/reconciliation"]].map(([title,description,href])=><Link key={href} href={href} className="rounded-2xl border bg-white p-6 shadow-sm hover:border-blue-400"><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-slate-600">{description}</p></Link>)}</section></div>;
}
