import Link from "next/link";
import { serverFetch } from "@/lib/server-api";
import type { FinanceDashboardSummary, FinanceWallet, PartnerContract, PricingRule, SentinelFinanceDashboard } from "@/types/finance";
const money=(v:string)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(Number(v||0));
export default async function OpsFinanceDashboard({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }){
 const rawParams=await searchParams;
 const filters=new URLSearchParams();
 for(const key of ["date_from","date_to","organization","branch","service_session","payment_source","status"]){const value=rawParams[key];if(typeof value==="string"&&value.trim())filters.set(key,value.trim());}
 const dashboardPath=`/api/finance/sentinel-dashboard/${filters.size?`?${filters.toString()}`:""}`;
 const [summary,wallets,contracts,rules,sentinel]:[FinanceDashboardSummary,FinanceWallet[],PartnerContract[],PricingRule[],SentinelFinanceDashboard]=await Promise.all([serverFetch("/api/finance/summary/"),serverFetch("/api/finance/wallets/"),serverFetch("/api/finance/contracts/"),serverFetch("/api/finance/pricing-rules/"),serverFetch(dashboardPath)]);
 const activeContracts=contracts.filter(c=>c.status==="active");
 const lowWallets=wallets.filter(w=>{const c=activeContracts.find(x=>x.organization===w.organization);const r=rules.find(x=>x.contract===c?.id&&x.is_active);return r&&Number(w.spendable_balance)<Number(r.gross_amount)*5;});
 const cards=[["Active contracts",summary.active_contracts],["Active pricing rules",summary.pricing_rules],["Organisation wallets",summary.wallets],["Financial records",summary.financial_records],["Awaiting payment",summary.awaiting_payment],["Captured assessments",summary.captured]];
 return <div className="space-y-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Finance</h1><p className="mt-1 text-slate-600">Sentinel accounting, contracts, negotiated pricing, wallets, ledger and settlements.</p></div><div className="flex flex-wrap gap-2"><Link href="/ops/finance/sponsorships" className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Sponsorships</Link><Link href="/ops/finance/transfers" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Treasury transfers</Link><Link href="/ops/finance/founder-expenses" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Founder expenses</Link></div></div>
 <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-bold text-blue-950">Sentinel treasury position</h2><p className="mt-1 max-w-3xl text-sm text-blue-900">Sentinel-only funds and commitments. Afriophthalmics billing identity and partner receipts remain in the existing billing and funding controls and are not counted here.</p></div><p className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-blue-900">Calculated {new Date(sentinel.calculated_at).toLocaleString("en-GB")}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Verified cash received",sentinel.verified_sentinel_cash_received],["Available Sentinel funds",sentinel.available_sentinel_funds],["Reserved",sentinel.reserved_sentinel_funds],["Transferable surplus",sentinel.transferable_surplus],["Pending / unverified",sentinel.pending_unverified_funding],["Sponsored services spent",sentinel.sponsored_services_spent],["Clinic payables",sentinel.clinic_payables],["Service-partner payables",sentinel.service_partner_payables],["Settled clinic allocations",sentinel.settled_allocations],["Settled service-partner payments",sentinel.settled_service_partner_earnings],["Corrections / reversals",sentinel.refunds_reversals_corrections],["Safeguarded commitments",sentinel.safeguarded_committed_funds],["Approved transfer commitments",sentinel.approved_transfer_commitments],...Object.entries(sentinel.sponsorship_commitments).map(([status,value])=>[`Sponsorship · ${status}`,value])].map(([label,value])=><div key={label} className="rounded-xl bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{money(value)}</p></div>)}</div><p className="mt-4 text-xs text-blue-900"><strong>Transfer safeguard:</strong> {sentinel.formula}</p></section>
 <form className="grid gap-3 rounded-2xl border bg-white p-5 text-sm md:grid-cols-4 xl:grid-cols-7"><label>Date from<input name="date_from" type="date" defaultValue={sentinel.applied_filters.date_from} className="mt-1 w-full rounded-lg border p-2" /></label><label>Date to<input name="date_to" type="date" defaultValue={sentinel.applied_filters.date_to} className="mt-1 w-full rounded-lg border p-2" /></label><label>Organisation ID<input name="organization" inputMode="numeric" defaultValue={sentinel.applied_filters.organization} className="mt-1 w-full rounded-lg border p-2" /></label><label>Branch ID<input name="branch" inputMode="numeric" defaultValue={sentinel.applied_filters.branch} className="mt-1 w-full rounded-lg border p-2" /></label><label>Session ID<input name="service_session" inputMode="numeric" defaultValue={sentinel.applied_filters.service_session} className="mt-1 w-full rounded-lg border p-2" /></label><label>Payment source<select name="payment_source" defaultValue={sentinel.applied_filters.payment_source} className="mt-1 w-full rounded-lg border p-2"><option value="">All verified sources</option><option value="paystack">Paystack</option><option value="bank_transfer">Bank transfer</option></select></label><label>Status<input name="status" defaultValue={sentinel.applied_filters.status} placeholder="e.g. captured" className="mt-1 w-full rounded-lg border p-2" /></label><div className="flex gap-2 md:col-span-4 xl:col-span-7"><button className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white">Apply filters</button><Link href="/ops/finance" className="rounded-lg border px-4 py-2 font-semibold">Clear</Link></div><p className="text-xs text-slate-500 md:col-span-4 xl:col-span-7">Date/source filters apply to receipt activity; encounter filters apply to sponsorship activity. Current wallet, liability and transfer-safety balances remain point-in-time controls.</p></form>
 {lowWallets.length?<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-950">Low-balance organisations</h2><p className="mt-1 text-sm text-amber-900">These wallets hold fewer than five assessments at the current negotiated price.</p><div className="mt-3 flex flex-wrap gap-2">{lowWallets.map(w=><span key={w.id} className="rounded-full bg-white px-3 py-1 text-sm font-semibold text-amber-900">{w.organization_name}: {money(w.spendable_balance)}</span>)}</div></section>:null}
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(([t,v])=><div key={String(t)} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-600">{t}</p><p className="mt-2 text-3xl font-bold">{v}</p></div>)}</section>
 <section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm text-slate-600">Total available wallet balance</p><p className="mt-2 text-3xl font-bold">{money(summary.wallet_available)}</p></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm text-slate-600">Total reserved wallet balance</p><p className="mt-2 text-3xl font-bold">{money(summary.wallet_reserved)}</p></div></section>
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Sponsorships","Fund approved encounters from genuine Sentinel money.","/ops/finance/sponsorships"],["Treasury transfers","Control and evidence manual Sentinel fund transfers.","/ops/finance/transfers"],["Founder-funded expenses","Record founder-paid Sentinel costs and controlled reimbursements.","/ops/finance/founder-expenses"],["Billing & bank settings","Configure the shared Afriophthalmics legal billing identity and transfer instructions.","/ops/finance/billing"],["Setup wizard","Onboard a hospital or clinic in one flow.","/ops/finance/setup"],["Contracts & pricing","Set organisation-specific assessment charges.","/ops/finance/contracts"],["Funding approvals","Verify and approve bank-transfer funding.","/ops/finance/funding"],["Service allowances","Control temporary pre-funding authority.","/ops/finance/allowances"],["Immutable ledger","Review every append-only wallet movement.","/ops/finance/ledger"],["Corrections","Maker–checker refunds and reversals.","/ops/finance/corrections"],["Settlements","Prepare, approve and evidence payouts.","/ops/finance/settlements"],["Reconciliation & audit","Investigate control consistency and history.","/ops/finance/reconciliation"]].map(([title,description,href])=><Link key={href} href={href} className="rounded-2xl border bg-white p-6 shadow-sm hover:border-blue-400"><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-slate-600">{description}</p></Link>)}</section></div>;
}
