"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { fetchEncounters, fetchMyOrganizationCapabilities } from "@/lib/api";
const pretty=(v?:string)=>v? v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()):"-";
export default function Page(){
 const [rows,setRows]=useState<any[]>([]),[profile,setProfile]=useState<any>(null),[source,setSource]=useState("all"),[error,setError]=useState("");
 useEffect(()=>{Promise.all([fetchEncounters(),fetchMyOrganizationCapabilities()]).then(([a,b])=>{setRows(a);setProfile(b)}).catch(e=>setError(e.message))},[]);
 const filtered=useMemo(()=>rows.filter(r=>source==="all"||r.source_type===source),[rows,source]);
 return <main className="sentinel-page space-y-6"><div className="flex justify-between gap-4"><div><h1 className="text-2xl font-bold">Retinal Assessments</h1><p className="text-sm text-slate-600">Clinic-direct and hospital-referred retinal assessments in one clinical workspace.</p></div>{profile?.clinic_direct_screening_enabled&&profile?.can_create_direct_patients?<Link href="/retinal-assessments/new" className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white">New Retinal Assessment</Link>:null}</div>{error?<p className="text-red-700">{error}</p>:null}<select value={source} onChange={e=>setSource(e.target.value)} className="rounded-xl border px-3 py-2"><option value="all">All sources</option><option value="clinic_direct">Clinic Direct</option><option value="hospital_referral">Hospital Referral</option></select><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-100"><tr>{["Encounter","Patient","Source","Hospital","Workflow","Payment","Status","Action"].map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="p-4 font-semibold">{r.encounter_id}</td><td className="p-4">{r.patient}</td><td className="p-4">{pretty(r.source_type)}</td><td className="p-4">{r.source_hospital_name||"-"}</td><td className="p-4">{pretty(r.workflow_route)}</td><td className="p-4">{pretty(r.payment_responsibility)}</td><td className="p-4">{pretty(r.screening_status)}</td><td className="p-4"><Link className="text-blue-700 underline" href={`/encounters/${r.id}`}>Open</Link></td></tr>)}</tbody></table></div></main>
}
