"use client";

import { useEffect, useState } from "react";
import { fetchEyeHealthReport, finalizeEyeHealthReport, previewEyeHealthReport, saveEyeHealthReport, startEyeHealthReportCorrection } from "@/lib/api";
import type { EyeHealthScreeningReport, TargetedScreeningFindings } from "@/types/report";
import type { OcularInvestigation } from "@/types/encounter";
import type { ImageUpload } from "@/types/upload";

const outcomes = [
  ["no_immediate_concern", "No immediate concern identified within the areas assessed"],
  ["routine_eye_examination", "Routine comprehensive eye examination advised"],
  ["further_assessment", "Further assessment recommended"],
  ["urgent_ophthalmology", "Urgent ophthalmology assessment recommended"],
  ["inconclusive_repeat", "Inconclusive — repeat testing required"],
] as const;
const adviceSuggestions = [
  "Continue routine comprehensive eye examinations.",
  "Arrange a comprehensive eye examination with an optometrist.",
  "Repeat visual-field testing to confirm reliability and reproducibility.",
  "Arrange optic-nerve assessment, including OCT RNFL where clinically available.",
  "Recheck intraocular pressure using an appropriate clinical method.",
  "Seek ophthalmology assessment.",
  "Seek urgent ophthalmology assessment.",
  "Continue diabetic retinal surveillance under the established diabetic programme.",
];
const emptyEye = { visual_field_reliability: "", visual_field_result: "", ght: "", cup_to_disc_ratio: "", vfi: "", other_machine_values: "" };
const emptyFindings: TargetedScreeningFindings = {
  fundus_quality: "", optic_disc: [], optic_disc_other: "", retinal_vessels: [], retinal_vessels_other: "",
  retina_macula: [], retina_macula_other: "", right: {...emptyEye}, left: {...emptyEye},
  iop_interpretation: "", iop_other: "", visual_acuity_interpretation: "", visual_acuity_other: "",
  clinical_interpretation: "", clinical_other: "",
};
const blank = {
  outcome: "", selected_advice: [] as string[], advice: "", structured_findings: emptyFindings,
  generated_suggestion: "", clinical_summary: "", right_visual_field_result: "", left_visual_field_result: "",
  right_fundus_result: "", left_fundus_result: "", selected_fundus_upload_ids: [] as number[],
  selected_visual_field_investigation_ids: [] as number[],
};
const choices = {
  quality: [["good","Good"],["mildly_limited","Mildly limited"],["significantly_limited","Significantly limited"],["ungradable","Ungradable"]],
  optic_disc: [["no_concerning_feature","No concerning disc feature identified"],["symmetrical_cupping","Symmetrical optic-disc cupping"],["asymmetrical_cupping","Asymmetrical optic-disc cupping"],["possible_physiological_cupping","Possible physiological cupping"],["rim_thinning_notching","Rim thinning or notching"],["disc_haemorrhage","Disc haemorrhage"],["other","Other clinician-entered finding"]],
  retinal_vessels: [["no_concerning_feature","No concerning vascular feature identified"],["av_nicking","Arteriovenous nicking"],["vascular_attenuation","Generalized vascular attenuation"],["other","Other clinician-entered finding"]],
  retina_macula: [["no_visible_abnormality","No visible abnormality within photographed area"],["retinal_haemorrhage","Retinal haemorrhage"],["retinal_exudate","Retinal exudate"],["cotton_wool_spot","Cotton-wool spot"],["macular_concern","Macular concern"],["other","Other clinician-entered finding"]],
  reliability: [["reliable","Reliable"],["reduced_reliability","Reduced reliability"],["unreliable","Unreliable"],["unable_to_assess","Unable to assess"],["not_performed","Not performed"]],
  field: [["within_expected_limits","Within expected limits"],["essentially_full","Essentially full"],["localized_reduction","Localized reduction"],["generalized_reduction","Generalized reduction"],["significant_abnormality","Significant abnormality"],["inconclusive","Inconclusive"],["not_performed","Not performed"]],
  ght: [["within_normal_limits","Within normal limits"],["borderline","Borderline"],["outside_normal_limits","Outside normal limits"],["unavailable","Unavailable"]],
  iop: [["within_expected_range","Within expected range"],["raised","Raised"],["asymmetrical","Asymmetrical"],["unavailable","Unavailable"],["other","Other clinician-entered interpretation"]],
  va: [["within_expected_range","Within expected range for recorded correction"],["reduced_right","Reduced in right eye"],["reduced_left","Reduced in left eye"],["reduced_both","Reduced in both eyes"],["asymmetrical","Asymmetrical"],["unable_to_assess","Unable to assess"],["other","Other clinician-entered interpretation"]],
  interpretation: [["no_immediate_concern","No immediate concern identified within the areas assessed"],["possible_physiological_cupping","Possible physiological optic-disc cupping"],["glaucoma_risk_features","Glaucoma-risk features identified"],["further_assessment","Further assessment recommended"],["urgent_ophthalmology","Urgent ophthalmology assessment recommended"],["inconclusive_repeat","Inconclusive — repeat testing required"],["other","Other clinician-entered interpretation"]],
} as const;

function Select({label,value,items,disabled,onChange}:{label:string;value:string;items:readonly (readonly [string,string])[];disabled:boolean;onChange:(v:string)=>void}) {
  return <label className="block text-sm font-medium">{label}<select disabled={disabled} value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Not recorded</option>{items.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>;
}

export default function EyeHealthScreeningReportForm({encounterId,uploads,investigations,canEdit,combined}:{encounterId:number;uploads:ImageUpload[];investigations:OcularInvestigation[];canEdit:boolean;combined:boolean}) {
  const [report,setReport]=useState<EyeHealthScreeningReport|null>(null);
  const [form,setForm]=useState(blank); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [signoff,setSignoff]=useState(false);
  useEffect(()=>{void fetchEyeHealthReport(encounterId).then((value)=>{setReport(value);if(value)setForm({
    outcome:value.outcome,selected_advice:value.selected_advice||[],advice:value.advice||"",
    structured_findings:{...emptyFindings,...(value.structured_findings||{}),right:{...emptyEye,...(value.structured_findings?.right||{})},left:{...emptyEye,...(value.structured_findings?.left||{})}},
    generated_suggestion:value.generated_suggestion||"",clinical_summary:value.clinical_summary||"",
    right_visual_field_result:value.right_visual_field_result||"",left_visual_field_result:value.left_visual_field_result||"",
    right_fundus_result:value.right_fundus_result||"",left_fundus_result:value.left_fundus_result||"",
    selected_fundus_upload_ids:value.selected_fundus_upload_ids||[],selected_visual_field_investigation_ids:value.selected_visual_field_investigation_ids||[],
  });}).catch((value)=>setError(value instanceof Error?value.message:"Unable to load report."));},[encounterId]);
  const locked=report?.status==="finalized"||!canEdit;
  const setFinding=(key:keyof TargetedScreeningFindings,value:string|string[])=>setForm((current)=>({...current,structured_findings:{...current.structured_findings,[key]:value}}));
  const setEye=(eye:"right"|"left",key:keyof typeof emptyEye,value:string)=>setForm((current)=>({...current,structured_findings:{...current.structured_findings,[eye]:{...current.structured_findings[eye],[key]:value}}}));
  const toggleFinding=(key:"optic_disc"|"retinal_vessels"|"retina_macula",value:string)=>{const current=form.structured_findings[key];setFinding(key,current.includes(value)?current.filter((item)=>item!==value):[...current,value]);};
  const toggleAsset=(field:"selected_fundus_upload_ids"|"selected_visual_field_investigation_ids",id:number)=>setForm((current)=>({...current,[field]:current[field].includes(id)?current[field].filter((value)=>value!==id):[...current[field],id]}));
  async function save(regenerate=false){setBusy(true);setError("");setMessage("");try{const value=await saveEyeHealthReport(encounterId,{...form,regenerate_suggested_wording:regenerate},report?.lock_version);setReport(value);setForm((current)=>({...current,generated_suggestion:value.generated_suggestion||"",clinical_summary:value.clinical_summary||current.clinical_summary}));setMessage(regenerate?"Suggested wording regenerated. Review and edit it before preview.":"Draft saved.");return value;}catch(value){setError(value instanceof Error?value.message:"Save failed.");return null;}finally{setBusy(false);}}
  async function preview(reportFormat:"patient"|"clinician"){const current=await save();if(!current)return;setBusy(true);try{const blob=await previewEyeHealthReport(current.id,reportFormat);const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000);setReport(await fetchEyeHealthReport(encounterId));}catch(value){setError(value instanceof Error?value.message:"Preview failed.");}finally{setBusy(false);}}
  async function finalize(){if(!report||!signoff)return setError("Confirm clinician sign-off after reviewing the preview.");setBusy(true);try{const value=await finalizeEyeHealthReport(report.id,report.lock_version);setReport(value);setMessage("Targeted Retinal and Glaucoma-Risk Screening Report finalized.");}catch(value){setError(value instanceof Error?value.message:"Finalization failed.");}finally{setBusy(false);}}
  async function startCorrection(){const reason=window.prompt("Enter the required clinical correction reason:","")?.trim();if(!report||!reason)return;setBusy(true);try{setReport(await startEyeHealthReportCorrection(report.id,reason));setSignoff(false);setMessage("Correction draft opened. The prior finalized version remains immutable.");}catch(value){setError(value instanceof Error?value.message:"Correction could not be started.");}finally{setBusy(false);}}
  const visualFields=investigations.filter((item)=>item.investigation_type==="visual_field"&&item.original_filename.toLowerCase().endsWith(".pdf"));
  return <div className="space-y-5">
    <p className="text-sm text-slate-600">Patient-facing targeted retinal and glaucoma-risk screening report. Measurements and observations never determine a diagnosis or outcome automatically.</p>
    {!report?.professional_defaults&&<p className="rounded border border-amber-300 bg-amber-50 p-3 text-sm">A verified professional profile is required before preview and sign-off.</p>}
    <section className="space-y-3 rounded border p-4"><h4 className="font-semibold">Photograph quality and observed findings</h4><Select label="Fundus image quality" value={form.structured_findings.fundus_quality} items={choices.quality} disabled={locked} onChange={(v)=>setFinding("fundus_quality",v)}/>{(["optic_disc","retinal_vessels","retina_macula"] as const).map((key)=><fieldset key={key} disabled={locked}><legend className="text-sm font-medium">{key.replaceAll("_"," ")}</legend>{choices[key].map(([value,label])=><label key={value} className="mt-1 flex gap-2 text-sm"><input type="checkbox" checked={form.structured_findings[key].includes(value)} onChange={()=>toggleFinding(key,value)}/>{label}</label>)}{form.structured_findings[key].includes("other")&&<textarea value={form.structured_findings[`${key}_other`]} onChange={(e)=>setFinding(`${key}_other`,e.target.value)} className="mt-2 w-full rounded border p-2" placeholder="Clinician-entered observation"/>}</fieldset>)}</section>
    <section className="space-y-3 rounded border p-4"><h4 className="font-semibold">Right/left visual-field observations</h4><div className="grid gap-4 md:grid-cols-2">{(["right","left"] as const).map((eye)=><div key={eye} className="space-y-2"><h5 className="font-medium capitalize">{eye} eye</h5><Select label="Reliability" value={form.structured_findings[eye].visual_field_reliability} items={choices.reliability} disabled={locked} onChange={(v)=>setEye(eye,"visual_field_reliability",v)}/><Select label="Observed result" value={form.structured_findings[eye].visual_field_result} items={choices.field} disabled={locked} onChange={(v)=>setEye(eye,"visual_field_result",v)}/><Select label="Glaucoma hemifield test" value={form.structured_findings[eye].ght} items={choices.ght} disabled={locked} onChange={(v)=>setEye(eye,"ght",v)}/>{(["cup_to_disc_ratio","vfi","other_machine_values"] as const).map((key)=><input key={key} disabled={locked} value={form.structured_findings[eye][key]} onChange={(e)=>setEye(eye,key,e.target.value)} className="w-full rounded border p-2 text-sm" placeholder={key.replaceAll("_"," ")}/>)}</div>)}</div></section>
    <section className="grid gap-3 rounded border p-4 md:grid-cols-3"><Select label="Eye-pressure interpretation" value={form.structured_findings.iop_interpretation} items={choices.iop} disabled={locked} onChange={(v)=>setFinding("iop_interpretation",v)}/><Select label="Visual-acuity interpretation" value={form.structured_findings.visual_acuity_interpretation} items={choices.va} disabled={locked} onChange={(v)=>setFinding("visual_acuity_interpretation",v)}/><Select label="Clinical interpretation" value={form.structured_findings.clinical_interpretation} items={choices.interpretation} disabled={locked} onChange={(v)=>setFinding("clinical_interpretation",v)}/></section>
    <button type="button" disabled={locked||busy} onClick={()=>void save(true)} className="rounded border px-4 py-2 font-semibold">Regenerate suggested wording</button>
    <label className="block text-sm font-medium">Clinician-confirmed clinical summary<textarea disabled={locked} value={form.clinical_summary} onChange={(e)=>setForm({...form,clinical_summary:e.target.value})} rows={7} className="mt-1 w-full rounded border p-2"/><span className="text-xs text-slate-500">Regeneration is explicit and replaces this box; ordinary selection changes never overwrite your edits.</span></label>
    <label className="block text-sm font-medium">Outcome<select disabled={locked} value={form.outcome} onChange={(e)=>setForm({...form,outcome:e.target.value})} className="mt-1 w-full rounded border p-2"><option value="">Select clinician-confirmed outcome</option>{outcomes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <fieldset disabled={locked} className="space-y-2"><legend className="text-sm font-medium">Suggested next steps</legend>{adviceSuggestions.map((item)=><label key={item} className="flex gap-2 text-sm"><input type="checkbox" checked={form.selected_advice.includes(item)} onChange={(e)=>setForm((current)=>({...current,selected_advice:e.target.checked?[...current.selected_advice,item]:current.selected_advice.filter((value)=>value!==item),advice:e.target.checked?[current.advice,item].filter(Boolean).join("\n"):current.advice}))}/>{item}</label>)}</fieldset>
    <label className="block text-sm font-medium">Editable recommended next steps<textarea disabled={locked} value={form.advice} onChange={(e)=>setForm({...form,advice:e.target.value})} rows={4} className="mt-1 w-full rounded border p-2"/></label>
    <div className="grid gap-3 md:grid-cols-2">{(["right","left"] as const).map((eye)=><div key={eye} className="space-y-2 rounded border p-3"><h4 className="font-semibold capitalize">{eye} eye clinician notes</h4><textarea disabled={locked} value={form[`${eye}_visual_field_result`]} onChange={(e)=>setForm({...form,[`${eye}_visual_field_result`]:e.target.value})} placeholder="Clinician-confirmed visual-field result" className="w-full rounded border p-2"/><textarea disabled={locked} value={form[`${eye}_fundus_result`]} onChange={(e)=>setForm({...form,[`${eye}_fundus_result`]:e.target.value})} placeholder="Clinician-confirmed fundus result" className="w-full rounded border p-2"/></div>)}</div>
    <fieldset disabled={locked} className="space-y-2"><legend className="font-medium">Explicitly selected fundus images</legend>{uploads.map((item)=><label key={item.id} className="flex gap-2 text-sm"><input type="checkbox" checked={form.selected_fundus_upload_ids.includes(item.id)} onChange={()=>toggleAsset("selected_fundus_upload_ids",item.id)}/>{item.eye_laterality} eye · image {item.id}</label>)}{!uploads.length&&<p className="text-sm text-slate-500">No fundus images available.</p>}</fieldset>
    <fieldset disabled={locked} className="space-y-2"><legend className="font-medium">Visual-field PDF attachments (order selected)</legend>{visualFields.map((item)=><label key={item.id} className="flex gap-2 text-sm"><input type="checkbox" checked={form.selected_visual_field_investigation_ids.includes(item.id)} onChange={()=>toggleAsset("selected_visual_field_investigation_ids",item.id)}/>{item.laterality} · {item.test_type||item.original_filename}</label>)}{!visualFields.length&&<p className="text-sm text-slate-500">No eligible visual-field PDFs available.</p>}</fieldset>
    {report?.professional_defaults&&<p className="rounded bg-slate-50 p-3 text-sm"><strong>Sign-off:</strong> {report.professional_defaults.display_name} · {report.professional_defaults.professional_role} · {report.professional_defaults.registration_number}</p>}
    {report?.status!=="finalized"&&canEdit&&<><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void save()} className="rounded border px-4 py-2 font-semibold">Save draft</button><button disabled={busy} onClick={()=>void preview("patient")} className="rounded bg-slate-800 px-4 py-2 font-semibold text-white">Preview Patient Report</button><button disabled={busy} onClick={()=>void preview("clinician")} className="rounded bg-slate-800 px-4 py-2 font-semibold text-white">Preview Clinician Report</button></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={signoff} onChange={(e)=>setSignoff(e.target.checked)}/>I confirm the professional sign-off after reviewing the current preview.</label><button disabled={busy||!signoff||!report?.previewed_at} onClick={()=>void finalize()} className="rounded bg-blue-700 px-4 py-2 font-semibold text-white disabled:opacity-50">Finalize immutable report</button></>}
    {report?.status==="finalized"&&<div className="space-y-2"><div className="flex flex-wrap gap-2">{report.clean_pdf_ready?<><a href={`${process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000"}/api/reports/eye-health/${report.id}/pdf/?report_format=patient`} target="_blank" rel="noreferrer" className="rounded bg-blue-700 px-4 py-2 font-semibold text-white">Download Patient Report</a><a href={`${process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000"}/api/reports/eye-health/${report.id}/pdf/?report_format=clinician`} target="_blank" rel="noreferrer" className="rounded bg-blue-700 px-4 py-2 font-semibold text-white">Download Clinician Report</a>{combined&&<><a href={`${process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000"}/api/reports/eye-health/combined/${encounterId}/bundle/?report_format=patient`} target="_blank" rel="noreferrer" className="rounded border px-4 py-2 font-semibold">Download Combined Patient Bundle</a><a href={`${process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000"}/api/reports/eye-health/combined/${encounterId}/bundle/?report_format=clinician`} target="_blank" rel="noreferrer" className="rounded border px-4 py-2 font-semibold">Download Combined Clinician Bundle</a></>}</>:<><button disabled={busy} onClick={()=>void preview("patient")} className="rounded border px-4 py-2 font-semibold">Preview Patient Report</button><button disabled={busy} onClick={()=>void preview("clinician")} className="rounded border px-4 py-2 font-semibold">Preview Clinician Report</button></>}{canEdit&&<button type="button" disabled={busy} onClick={()=>void startCorrection()} className="rounded border px-4 py-2 font-semibold">Start controlled correction</button>}</div>{!report.clean_pdf_ready&&<p className="text-sm text-amber-700">Clean downloads remain unavailable until encounter completion and the applicable funding, capture, authorization, and release controls pass.</p>}</div>}
    {message&&<p className="rounded bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}{error&&<p className="rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}
  </div>;
}
