"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { fetchOpsEyeHealthReport, reviewOpsEyeHealthReport } from "@/lib/clinical-report-ops";

export default function OpsEyeHealthReviewPage({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState(""); const [data, setData] = useState<any>(null); const [note, setNote] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load(value: string) { setData(await fetchOpsEyeHealthReport(value)); }
  useEffect(() => { params.then(({ id }) => { setId(id); load(id).catch((e) => setMessage(e instanceof Error ? e.message : "Unable to load report.")); }); }, [params]);
  async function act(decision: "approve" | "return") { if (decision === "return" && !note.trim()) return setMessage("A return reason is required."); setBusy(true); setMessage(""); try { await reviewOpsEyeHealthReport(id, decision, note); await load(id); setNote(""); setMessage(decision === "approve" ? "Clinician-signed targeted report approved and issued by Ops." : "Report returned to clinic for correction."); } catch (e) { setMessage(e instanceof Error ? e.message : "Review failed."); } finally { setBusy(false); } }
  if (!data) return <main className="p-8">{message || "Loading targeted report..."}</main>;
  const report = data.report; const snapshot = data.signed_snapshot || {}; const clinician = data.signed_clinician || {}; const context = data.context || {}; const awaiting = report.review_status === "awaiting_ops" || report.review_status === "legacy";
  return <main className="space-y-6"><div className="flex justify-between gap-4"><div><h1 className="text-3xl font-bold">Targeted Retinal & Glaucoma-Risk Review</h1><p className="text-slate-600">{context.encounter_reference} · {context.patient_name}</p></div><Link href="/ops/reports" className="rounded border bg-white px-4 py-2">Back to queue</Link></div>
    {message ? <div className="rounded border bg-white p-3 text-sm">{message}</div> : null}
    <section className="grid gap-4 md:grid-cols-3"><Card title="Context"><p>Patient: {context.patient_name}</p><p>Clinic: {context.clinic_name || "-"}</p><p>Hospital: {context.hospital_name || "-"}</p></Card><Card title="Status"><p>Clinical status: {report.status}</p><p>Ops review: {report.review_status}</p><p>Submitted: {report.submitted_to_ops_at || "-"}</p></Card><Card title="Responsible clinician"><p>{clinician.signature_name || clinician.display_name || "-"}</p><p>{clinician.professional_role || "-"}</p><p>{[clinician.registration_body, clinician.registration_number].filter(Boolean).join(" ") || "-"}</p></Card></section>
    <section className="rounded-xl bg-white p-6 shadow"><h2 className="mb-4 text-xl font-bold">Signed clinical version</h2><JsonClinicalSnapshot snapshot={snapshot} /></section>
    <section className="rounded-xl bg-white p-6 shadow"><h2 className="mb-3 text-xl font-bold">Ops review action</h2><p className="mb-4 text-sm text-slate-600">The clinician has already signed this version. Ops approval does not replace the clinical signer.</p><textarea disabled={!awaiting || busy} value={note} onChange={(e) => setNote(e.target.value)} placeholder="Ops review note / required correction" className="w-full rounded border p-3" rows={4}/><div className="mt-4 flex gap-3"><button disabled={!awaiting || busy || !note.trim()} onClick={() => void act("return")} className="rounded bg-amber-600 px-4 py-2 font-semibold text-white disabled:opacity-50">Return to clinic</button><button disabled={!awaiting || busy} onClick={() => void act("approve")} className="rounded bg-emerald-700 px-4 py-2 font-semibold text-white disabled:opacity-50">Approve & issue</button></div></section>
  </main>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-xl border bg-white p-4"><h2 className="font-semibold">{title}</h2><div className="mt-2 space-y-1 text-sm text-slate-700">{children}</div></div>; }
function JsonClinicalSnapshot({ snapshot }: { snapshot: Record<string, any> }) { const findings = snapshot.structured_findings || {}; return <div className="space-y-3 text-sm"><p><strong>Outcome:</strong> {snapshot.outcome || "-"}</p><p><strong>Clinical summary:</strong> {snapshot.clinical_summary || snapshot.generated_suggestion || "-"}</p><p><strong>Advice:</strong> {snapshot.advice || (snapshot.selected_advice || []).join("; ") || "-"}</p><details className="rounded border bg-slate-50 p-3"><summary className="cursor-pointer font-semibold">Structured findings</summary><pre className="mt-3 overflow-x-auto whitespace-pre-wrap text-xs">{JSON.stringify(findings, null, 2)}</pre></details></div>; }
