"use client";

import { useState } from "react";
import { downloadFinanceFile, financeWrite, financeWriteForm } from "@/lib/finance-api";
import type {
  ServicePartnerAdjustment, ServicePartnerCorrection, ServicePartnerEarning,
  ServicePartnerPayableSummary, ServicePartnerSettlement,
} from "@/types/finance";

const money = (value: string | null, currency: string) =>
  new Intl.NumberFormat("en-NG", { style: "currency", currency }).format(Number(value || 0));

export default function PayablesManager({ earnings, summary, settlements, adjustments, corrections, canPrepare, canApprove }: {
  earnings: ServicePartnerEarning[]; summary: ServicePartnerPayableSummary[];
  settlements: ServicePartnerSettlement[]; adjustments: ServicePartnerAdjustment[];
  corrections: ServicePartnerCorrection[]; canPrepare: boolean; canApprove: boolean;
}) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  async function action(path: string, body: unknown) {
    setBusy(true); setError("");
    try { await financeWrite(path, "POST", body); location.reload(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Finance action failed."); setBusy(false); }
  }
  async function markPaid(id: number, file: File | null) {
    const paymentDate = prompt("Payment date (YYYY-MM-DD)");
    const reference = prompt("External payment reference");
    if (!paymentDate || !reference) return;
    const data = new FormData(); data.append("payment_date", paymentDate); data.append("external_reference", reference);
    if (file) data.append("evidence", file);
    setBusy(true); setError("");
    try { await financeWriteForm(`/api/finance/internal/service-partner-payables/${id}/mark-paid/`, data); location.reload(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to record payment."); setBusy(false); }
  }
  return <div className="space-y-7">
    <div><h1 className="text-3xl font-bold">Service-partner payables</h1><p className="mt-1 text-slate-600">Assessment earnings and controlled daily payments. No patient or clinical information is shown.</p></div>
    {error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="grid gap-4 md:grid-cols-3">{summary.length ? summary.map(row => <section key={`${row.service_partner_id}-${row.currency}`} className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">{row.service_partner__name}</h2><p className="mt-3 text-sm">Gross earned <strong>{money(row.total_earned, row.currency)}</strong></p><p className="text-sm">Paid <strong>{money(row.total_paid, row.currency)}</strong></p><p className="text-sm">Outstanding <strong>{money(row.outstanding, row.currency)}</strong></p><p className="text-sm text-amber-700">Carried adjustment <strong>{money(row.carried_forward_adjustment, row.currency)}</strong></p><p className="mt-2 text-xs text-slate-500">{row.unpaid_assessments} unpaid · oldest {row.oldest_outstanding_date || "—"}</p></section>) : <p className="text-slate-500">No service-partner earnings yet.</p>}</div>
    {canPrepare && summary.some(row => row.unpaid_assessments > 0) && <form className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-3" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); action("/api/finance/internal/service-partner-payables/prepare/", { service_partner: Number(data.get("partner")), assessment_date: data.get("date") }); }}><select required name="partner" className="rounded border p-2"><option value="">Service partner</option>{summary.filter(row => row.unpaid_assessments > 0).map(row => <option key={row.service_partner_id} value={row.service_partner_id}>{row.service_partner__name}</option>)}</select><input required name="date" type="date" className="rounded border p-2"/><button disabled={busy} className="rounded bg-blue-700 px-4 py-2 font-semibold text-white">Prepare daily settlement</button></form>}
    <section><h2 className="mb-3 text-xl font-bold">Earnings</h2><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Reference</th><th className="p-3">Session / assessment</th><th className="p-3">Date</th><th className="p-3">Provider</th><th className="p-3 text-right">Rate</th><th className="p-3">Earned</th><th className="p-3">Status</th></tr></thead><tbody>{earnings.length ? earnings.map(row => <tr key={row.id} className="border-t"><td className="p-3 font-mono text-xs">{row.earning_reference}</td><td className="p-3"><div>{row.session_reference}</div><div className="font-mono text-xs text-slate-500">{row.encounter_reference}</div></td><td className="p-3">{row.assessment_date}</td><td className="p-3">{row.service_partner_name}</td><td className="p-3 text-right">{money(row.amount, row.currency)}</td><td className="p-3">{new Date(row.earned_at).toLocaleDateString()}</td><td className="p-3">{row.status.replaceAll("_", " ")}</td></tr>) : <tr><td colSpan={7} className="p-8 text-center text-slate-500">No qualifying assessments.</td></tr>}</tbody></table></div></section>
    {canPrepare && <section><h2 className="mb-3 text-xl font-bold">Request earning correction</h2><form className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-3" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); action("/api/finance/internal/service-partner-payables/request-correction/", { earning: Number(data.get("earning")), amount: data.get("amount"), reason: data.get("reason") }); }}><select required name="earning" className="rounded border p-2"><option value="">Original earning</option>{earnings.map(row => <option key={row.id} value={row.id}>{row.earning_reference} · {row.service_partner_name}</option>)}</select><input required name="amount" min="0.01" step="0.01" placeholder="Correction amount" className="rounded border p-2"/><input required name="reason" placeholder="Invalid-earning reason" className="rounded border p-2"/><button disabled={busy} className="rounded bg-amber-700 px-4 py-2 font-semibold text-white">Request correction</button></form></section>}
    <section><h2 className="mb-3 text-xl font-bold">Corrections and carried adjustments</h2><div className="space-y-3">{corrections.length ? corrections.map(row => <article key={row.id} className="rounded-2xl border bg-white p-4 text-sm"><div className="flex flex-wrap justify-between gap-3"><div><strong>{row.earning_reference}</strong> · {money(row.amount, row.adjustment?.currency || "NGN")} · {row.status}<p className="text-slate-600">{row.reason}</p>{row.adjustment && <p className="text-amber-700">Adjustment {money(row.adjustment.amount, row.adjustment.currency)} · {row.adjustment.status.replaceAll("_", " ")}</p>}</div>{row.status === "pending" && canApprove && <div className="flex gap-2"><button disabled={busy} onClick={() => action(`/api/finance/internal/service-partner-payables/${row.id}/approve-correction/`, {})} className="rounded bg-green-700 px-3 py-1.5 text-xs text-white">Approve correction</button><button disabled={busy} onClick={() => { const reason = prompt("Rejection reason"); if (reason) action(`/api/finance/internal/service-partner-payables/${row.id}/reject-correction/`, { reason }); }} className="rounded bg-red-700 px-3 py-1.5 text-xs text-white">Reject</button></div>}</div></article>) : <p className="rounded-2xl border bg-white p-6 text-center text-slate-500">No correction requests.</p>}</div><p className="mt-2 text-xs text-slate-500">{adjustments.length} immutable compensating adjustment(s) recorded.</p></section>
    <section><h2 className="mb-3 text-xl font-bold">Payment history</h2><div className="space-y-3">{settlements.length ? settlements.map(batch => <article key={batch.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{batch.service_partner_name} · {batch.assessment_date}</h3><p className="text-sm text-slate-600">{batch.assessment_count} assessments · {money(batch.final_amount, batch.currency)} · {batch.status}</p><p className="text-xs text-slate-500">Sessions: {batch.included_sessions.join(", ")}</p></div><div className="flex flex-wrap gap-2">{batch.status === "draft" && canApprove && <><button disabled={busy} onClick={() => action(`/api/finance/internal/service-partner-payables/${batch.id}/approve/`, {})} className="rounded bg-green-700 px-3 py-1.5 text-xs text-white">Approve</button><button disabled={busy} onClick={() => { const reason = prompt("Rejection reason"); if (reason) action(`/api/finance/internal/service-partner-payables/${batch.id}/reject/`, { reason }); }} className="rounded bg-red-700 px-3 py-1.5 text-xs text-white">Reject</button></>}{batch.status === "draft" && canPrepare && <button disabled={busy} onClick={() => { const reason = prompt("Cancellation reason"); if (reason) action(`/api/finance/internal/service-partner-payables/${batch.id}/cancel/`, { reason }); }} className="rounded border px-3 py-1.5 text-xs">Cancel</button>}{batch.status === "approved" && canPrepare && <label className="cursor-pointer rounded bg-blue-700 px-3 py-1.5 text-xs text-white">Mark paid<input className="hidden" type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={event => markPaid(batch.id, event.target.files?.[0] || null)}/></label>}{batch.has_payment_evidence && <button disabled={busy} onClick={() => downloadFinanceFile(`/api/finance/internal/service-partner-payables/${batch.id}/payment-evidence/`, `partner-settlement-${batch.id}-evidence`)} className="rounded border px-3 py-1.5 text-xs">Download evidence</button>}</div></div></article>) : <p className="rounded-2xl border bg-white p-8 text-center text-slate-500">No daily settlements.</p>}</div></section>
  </div>;
}
